'use server'

import { createClient } from '@/lib/supabase/server'
import type {
  Customer,
  Consultation,
  RecentConsultation,
  CreateConsultationResult,
  CreateCustomerResult,
  SearchResult,
  ConsultationHistoryResult,
  RecentConsultationsResult,
} from './types'

export async function searchCustomers(query: string): Promise<SearchResult> {
  const supabase = createClient()

  if (!query || query.length < 2) {
    return { customers: [], error: null }
  }

  const { data, error } = await supabase
    .from('customers')
    .select('id, name, phone, address, created_at, is_preferred_client')
    .or(
      `name.ilike.%${query}%,phone.ilike.%${query}%,address.ilike.%${query}%`
    )
    .order('created_at', { ascending: false })
    .limit(10)

  if (error) {
    return { customers: [], error: error.message }
  }

  return { customers: (data || []) as Customer[], error: null }
}

export async function getCustomerById(customerId: string): Promise<{
  customer: Customer | null
  error: string | null
}> {
  const supabase = createClient()

  const { data, error } = await supabase
    .from('customers')
    .select('id, name, phone, address, created_at, is_preferred_client')
    .eq('id', customerId)
    .single()

  if (error) {
    return { customer: null, error: error.message }
  }

  return { customer: data as Customer, error: null }
}

export async function isReturningCustomer(customerId: string): Promise<{
  isReturning: boolean
  count: number
}> {
  const supabase = createClient()

  const { count, error } = await supabase
    .from('consultations')
    .select('*', { count: 'exact', head: true })
    .eq('customer_id', customerId)

  if (error) {
    return { isReturning: false, count: 0 }
  }

  return { isReturning: (count || 0) > 0, count: count || 0 }
}

export async function getConsultationHistory(
  customerId: string,
  limit: number = 5
): Promise<ConsultationHistoryResult> {
  const supabase = createClient()

  const { data, error } = await supabase
    .from('consultations')
    .select('id, consultation_number, status, notes, completed_at, created_at')
    .eq('customer_id', customerId)
    .order('created_at', { ascending: false })
    .limit(limit)

  if (error) {
    return { consultations: [], error: error.message }
  }

  return { consultations: (data || []) as Consultation[], error: null }
}

export async function getRecentConsultations(
  limit: number = 5
): Promise<RecentConsultationsResult> {
  const supabase = createClient()

  const { data, error } = await supabase
    .from('consultations')
    .select(
      `id, consultation_number, status, created_at,
       customers(id, name, phone)`
    )
    .order('created_at', { ascending: false })
    .limit(limit)

  if (error) {
    return { consultations: [], error: error.message }
  }

  return { consultations: (data || []) as unknown as RecentConsultation[], error: null }
}

export async function createNewCustomer(
  name: string,
  phone: string,
  address?: string
): Promise<CreateCustomerResult> {
  const supabase = createClient()
  const user = await supabase.auth.getUser()

  if (!user.data.user?.id) {
    return { success: false, error: 'Not authenticated', customer: null }
  }

  const { data, error } = await supabase
    .from('customers')
    .insert({
      name,
      phone,
      address: address || null,
      created_by: user.data.user.id,
    })
    .select('id, name, phone, address, created_at, is_preferred_client')
    .single()

  if (error) {
    // Postgres unique violation code
    if (error.code === '23505') {
      return { success: false, error: 'Nomor HP sudah terdaftar.', customer: null }
    }
    return { success: false, error: error.message, customer: null }
  }

  return { success: true, error: null, customer: data as Customer }
}

export async function createConsultationSession(
  customerId: string,
  notes?: string
): Promise<CreateConsultationResult> {
  const supabase = createClient()
  const user = await supabase.auth.getUser()

  if (!user.data.user?.id) {
    return {
      success: false,
      error: 'Not authenticated',
      consultationId: null,
      consultationNumber: null,
    }
  }

  // consultation_number generated by DB via generate_consultation_number()
  const { data, error } = await supabase
    .from('consultations')
    .insert({
      customer_id: customerId,
      notes: notes || '',
      status: 'check_in',
      created_by: user.data.user.id,
    })
    .select('id, consultation_number')
    .single()

  if (error) {
    return {
      success: false,
      error: error.message,
      consultationId: null,
      consultationNumber: null,
    }
  }

  return {
    success: true,
    error: null,
    consultationId: data.id,
    consultationNumber: data.consultation_number,
  }
}